INSERT INTO restaurants (name, description, address, rating, restaurant_type, num_of_reviews, image_url)
VALUES
  ('Chicken Rice Express', 'Famous for Hainanese Chicken Rice', '123 Orchard Road, Singapore', 4.9, 'Chicken', 1769, 'https://upload.wikimedia.org/wikipedia/en/thumb/d/d4/The_Chicken_Rice_Shop_logo.svg/1200px-The_Chicken_Rice_Shop_logo.svg.png'),
  ('China Noodle Delight', 'Specializing in various noodle dishes', '456 Raffles Place, Singapore', 4.8, 'Chinese', 24322, 'https://cdn.concreteplayground.com/content/uploads/2016/01/Chinese-Noodle-House-CP-Trent-van-der-Jagt-2-1440x1440.jpg'),
  ('Sushi Haven', 'Authentic Japanese sushi and sashimi', '789 Marina Bay Sands, Singapore', 4.7, 'Japanese', 16381, 'https://img.cdn4dd.com/cdn-cgi/image/fit=contain,width=1200,height=672,format=auto/https://doordash-static.s3.amazonaws.com/media/restaurant/cover_square/4426b5dc-c7f2-46ee-8e01-79b5085d0af2.png'),
  ('Korean Spicy Noodle House', 'Home of spicy noodle lovers', '101 Tanjong Pagar Road, Singapore', 4.6, 'Korean', 16111, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUjZAZ6C0cIw9_x6o3Y5PPrc8uJOEFb2mlhQ&usqp=CAU'),
  ('Pizza Paradise', 'Delicious pizzas with a variety of toppings', '202 Sentosa Island, Singapore', 4.5, 'Pizza', 7544, 'https://content.jdmagicbox.com/comp/hoshangabad/s2/9999p7574.7574.180831231822.c9s2/catalogue/pizza-paradise-hoshangabad-pizza-outlets-8hp33a7krp.jpg'),
  ('Curry House', 'Flavorful Indian curries', '303 Little India, Singapore', 4.4, 'Indian', 16869, 'https://media-cdn.tripadvisor.com/media/photo-s/0d/f1/c8/ca/photo0jpg.jpg'),
  ('Thai Delights', 'Traditional Thai dishes with a modern twist', '404 Chinatown, Singapore', 4.3, 'Thai', 9733, 'https://sethlui.com/wp-content/uploads/2021/10/Cheap-Thai-Hawkers-Sisaket-Thai-Food-1.jpg'),
  ('Dessert Dreamland', 'Satisfy your sweet tooth with our desserts', '505 Bugis Street, Singapore', 4.2, 'Dessert', 4544, 'https://pbs.twimg.com/profile_images/1195989102367297536/cXd86MJA_400x400.jpg'),
  ('Healthy Bites', 'Nutritious and delicious healthy options', '606 Orchard Boulevard, Singapore', 4.1, 'Healthy', 24101, 'https://www.thetncard.com/uploads/Screenshot%202021-05-04%20at%2014.37.24.png'),
  ('Western Grill', 'Classic Western dishes for all tastes', '707 Clarke Quay, Singapore', 5.0, 'Western', 19615, 'https://www.minorfoodsingapore.com/wp-content/uploads/2020/07/XW-Western-Grill-@-JEM-Exterior.jpg'),
  ('Satay Street', 'Famous for delicious satay skewers', '111 Marina Bay, Singapore', 4.9, 'Satay', 21303, 'https://i.ytimg.com/vi/Kbadx8Yg9nQ/sddefault.jpg'),
  ('Dim Sum Delight', 'Authentic Cantonese dim sum experience', '222 Chinatown, Singapore', 4.8, 'Chinese', 2886, 'https://robina.com.au/cbdrobina_website/wp-content/uploads/dim-sum-2-1.jpg'),
  ('Ramen House', 'Specializing in various ramen varieties', '333 Orchard Road, Singapore', 3.8, 'Japanese', 29825, 'https://i.pinimg.com/736x/21/37/6f/21376fdf575f567906d469dde5222c73.jpg'),
  ('Mexican Maze', 'Specializing in texmex cuisines', '84 Beach Road, Singapore', 4.7, 'Japanese', 15736, 'https://tb-static.uber.com/prod/image-proc/processed_images/31ecbcc6ddf0e68043e45925ef8a9d91/3ac2b39ad528f8c8c5dc77c59abb683d.jpeg'),
  ('Vegetarian Paradise', 'Specializing in Vegetarian cuisines', '200 Toa Payoh North, Singapore', 4.6, 'Vegetarian', 15568, 'https://longdan.co.uk/cdn/shop/articles/vegan-vegetarian-paradise.jpg?v=1700554704'),
  ('Vegan Delights', 'Specializing in Vegan cuisines', '754 Changi Road, Singapore', 4.6, 'Vegan', 18528, 'https://scontent.fsin15-1.fna.fbcdn.net/v/t39.30808-6/272039128_2134774760032394_789618513329331116_n.jpg?_nc_cat=109&ccb=1-7&_nc_sid=5f2048&_nc_ohc=SUZ9_kbdDM0AX9sHF3e&_nc_ht=scontent.fsin15-1.fna&oh=00_AfCoaatsac_L0JvKO6PSfPjrUHgag2_eXtxBbVrqLZggiA&oe=66030C67');





INSERT INTO dishes (restaurant_id, is_available, name, description, price, diet_type, cuisine, image_url)
VALUES

  -- Chicken Rice Express
  (1, true, 'Hainanese Chicken Rice', 'Classic Hainanese chicken with fragrant rice', 5.50, 'normal', '{"singaporean", "chinese", "rice"}', 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Hainanese_Chicken_Rice.jpg/800px-Hainanese_Chicken_Rice.jpg'),
  (1, true, 'Roast Chicken Noodles', 'Roasted chicken served with noodles', 6.50, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://ykgi.com.sg/wp-content/uploads/2018/09/Roasted-Chicken-Noodle-1080x675.jpg'),
  (1, true, 'Chicken Satay Rice', 'Hainanese-style chicken rice with chicken satay', 8.50, 'normal', '{"singaporean", "chinese", "rice"}','https://img.taste.com.au/fUzjItER/taste/2016/11/chicken-satay-sticks-with-jasmine-rice-76144-1.jpeg'),
  (1, true, 'Spicy Chicken Noodles', 'Spicy chicken noodles with a kick', 7.00, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://images.aws.nestle.recipes/resized/c03e27970983af8480a795f7d9f6c8bb_spicy-chicken-noodles_944_531.jpg'),
  (1, true, 'Chicken Rice Vermicelli Soup', 'Tender chicken, rice vermicelli noodles, and soup broth', 7.50, 'normal', '{"singaporean", "chinese", "soup", "noodles"}', 'https://ahintofrosemary.com/wp-content/uploads/2020/05/IMG_0829.jpg'),
  (1, true, 'Black Pepper Chicken Rice Bowl', 'Savory chicken in a black pepper sauce served over rice', 9.00, 'normal', '{"singaporean", "chinese", "rice"}', 'https://lh5.googleusercontent.com/I1JY1xzIUNTofFG5blyrT0NWD-ZiHwbMvxNtNRop_YT5xo_Pz-10wzQQ_BY90Ukrj1Kjwdt0z6aAE2woGrbpGP4xQxGXLdT5zxN2KldDXNKN-iMr60H7iH5KieDNvns6cjvAxD-i=s0'),
  (1, true, 'Sesame Ginger Chicken Salad', 'Grilled chicken with sesame ginger dressing on a bed of greens', 8.00, 'normal', '{"singaporean", "chinese", "healthy"}', 'https://emeals-menubuilder.s3.amazonaws.com/v1/recipes/778067/pictures/large_sesame-ginger-chicken-salad.jpeg'),
  (1, true, 'Chicken Rice Paper Rolls', 'Fresh rice paper rolls filled with chicken, herbs, and vegetables', 6.50, 'normal', '{"singaporean", "chinese"}', 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/6/6/0/FN_Chicken-Summer-Rolls_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371597708666.jpeg'),
  (1, true, 'Curry Chicken Rice', 'Tender chicken in a fragrant curry sauce served with rice', 8.50, 'normal', '{"singaporean", "chinese"}', 'https://www.jocooks.com/wp-content/uploads/2019/10/coconut-chicken-curry-1-10.jpg'),
  (1, true, 'Lemon Herb Roast Chicken', 'Juicy roast chicken seasoned with lemon and herbs', 10.00, 'normal', '{"singaporean", "chinese", "roast"}', 'https://www.lemonblossoms.com/wp-content/uploads/2018/02/Lemon-and-herb-roasted-chicken-S8.jpg'),
  (1, true, 'Chicken Congee', 'Traditional rice porridge with shredded chicken and aromatics', 6.00, 'normal', '{"singaporean", "chinese", "rice"}', 'https://delightfulplate.com/wp-content/uploads/2019/01/Pressure-Cooker-Vietnamese-Chicken-Congee-with-Brown-Rice-Chao-ga-2.jpg'),
  (1, true, 'Ginger Scallion Chicken Rice', 'Steamed chicken with ginger scallion sauce over rice', 7.50, 'normal', '{"singaporean", "chinese", "rice"}', 'https://static01.nyt.com/images/2024/02/07/multimedia/07korex-pfmq/05korex-pfmq-superJumbo.jpg'),

  -- China Noodle Delight
  (2, true, 'Singapore-style Noodles', 'Stir-fried noodles with prawns and vegetables', 8.00, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://www.seriouseats.com/thmb/BCVop4rdTQCA0HXRl_2NUHHMQJU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__05__20150424-singapore-noodles-shao-zhong-20-130b0ed9d8ad45b3bd164cbe1328abef.jpg'),
  (2, true, 'Beef Hor Fun', 'Flat rice noodles with beef in a savory sauce', 9.50, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://delishar.com/wp-content/uploads/2016/04/Dry-Beef-Hor-Fun-3.jpg'),
  (2, true, 'Char Kway Teow', 'Stir-fried flat rice noodles with prawns and chinese sausage', 10.00, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://christieathome.com/wp-content/uploads/2020/12/Char-Kway-Teow-28-scaled.jpg'),
  (2, true, 'Wonton Noodle Soup', 'Noodle soup with wontons and BBQ pork', 8.50, 'normal', '{"singaporean", "chinese", "noodles"}', 'https://www.elmundoeats.com/wp-content/uploads/2022/10/RC-Wonton-noodle-soup-in-a-bowl-view-from-up.jpg'),
  (2, true, 'Dan Dan Noodles', 'Spicy Sichuan noodles with minced pork and peanuts', 9.00, 'normal', '{"chinese", "noodles"}', 'https://tornadoughalli.com/wp-content/uploads/2021/12/DAN-DAN-NOODLES-5-1.jpg'),
  (2, true, 'Vegetable Lo Mein', 'Stir-fried noodles with assorted vegetables in a light soy sauce', 7.50, '{"vegetarian", "normal"}', '{"chinese", "noodles", "singaporean"}', 'https://www.savingdessert.com/wp-content/uploads/2015/04/Vegetable-Lo-Mein-9.jpg'),
  (2, true, 'Spicy Garlic Eggplant Noodles', 'Eggplant and noodles in a spicy garlic sauce', 8.50, 'normal', '{"chinese", "noodles", "spicy", "singaporean"}', 'https://assets.bonappetit.com/photos/60df22703fb7dfb44231815a/4:3/w_1496,h_1122,c_limit/0821-Spicy%20Braised%20Eggplant%20Noodles.jpg'),
  (2, true, 'Cold Sesame Noodles', 'Chilled noodles tossed in a sesame sauce with cucumber and sesame seeds', 8.00, 'normal', '{"chinese", "noodles", "cold"}', 'https://www.seriouseats.com/thmb/fIDd5_FOdYrc7i4eHLlBIOwhodk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20220720-Seasame-Noodles--Amanda-Suarez-Hero-53162bd767484e0aac39b833bc67be1a.JPG'),
  (2, true, 'Shanghai Stir-Fried Udon', 'Thick udon noodles stir-fried with pork, cabbage, and soy sauce', 9.50, 'normal', '{"chinese", "noodles", "udon"}', 'https://www.aheadofthyme.com/wp-content/uploads/2016/01/shanghai-fried-noodles-in-10-minutes-2.jpg'),
  (2, true, 'Seafood Noodle Soup', 'Noodle soup with assorted seafood and fish balls in a clear broth', 10.50, 'normal', '{"chinese", "noodles", "seafood", "singaporean"}', 'https://img.tastelife.tv/assets/uploads/2020/07/Seafood_Soup_Chef_John_01067_13-3.jpg'),
  (2, true, 'Szechuan Spicy Noodles', 'Hand-pulled noodles in a fiery Szechuan pepper sauce with minced meat', 9.00, 'normal', '{"chinese", "noodles", "spicy"}', 'https://rasamalaysia.com/wp-content/uploads/2017/09/spicy-sichuan-noodles-thumb.jpg'),
  (2, true, 'Hong Kong Soy Sauce Noodles', 'Egg noodles tossed in a savory soy sauce with char siu pork', 9.00, 'normal', '{"chinese", "noodles"}', 'https://omnivorescookbook.com/wp-content/uploads/2022/03/220224_Soy-Sauce-Pan-Fried-Noodles_6.jpg'),
  (2, true, 'Vegetable Chow Mein', 'Stir-fried noodles with mixed vegetables in a savory sauce', 7.00, '{"vegetarian", "normal"}', '{"chinese", "noodles", "singaporean"}', 'https://school-of-wok.s3.eu-west-2.amazonaws.com/recipes/show_images/f6b932a64e2972a1c62b3231d0219256.jpg'),
  (2, true, 'Tofu and Veggie Stir-Fry Noodles', 'Tofu and assorted veggies stir-fried with noodles in a light sauce', 8.50, '{"vegetarian", "normal"}', '{"chinese", "noodles", "singaporean"}', 'https://data.thefeedfeed.com/static/2022/01/04/164131052161d46939b553a.jpg'),


  -- Sushi Haven
  (3, true, 'Assorted Sushi Platter', 'Chef''s selection of fresh sushi', 12.00, 'normal', '{"japanese", "rice"}', 'https://feeds.oddle.me/wp-content/uploads/2022/06/Wakasa-500x500.png'),
  (3, true, 'Sashimi Deluxe', 'Premium slices of assorted sashimi', 15.00, 'normal', 'japanese', 'https://popmenucloud.com/cdn-cgi/image/width%3D1200%2Cheight%3D1200%2Cfit%3Dscale-down%2Cformat%3Dauto%2Cquality%3D60/emitwbsv/009643c6-22b4-4157-adc5-5c32246c4fa1.jpg'),
  (3, true, 'Chirashi Bowl', 'Assorted sashimi over a bed of sushi rice', 18.00, 'normal', '{"japanese", "rice"}', 'https://www.justonecookbook.com/wp-content/uploads/2020/04/Quick-Easy-Chirashi-Sushi-4117-I.jpg'),
  (3, true, 'Dragon Roll', 'Sushi roll with eel, avocado, and cucumber', 14.00, 'normal', '{"japanese", "rice"}', 'https://www.foodandwine.com/thmb/5m0L19cELC8zqZQGrcfhCTNY5jY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Dragon-Roll-FT-RECIPE0223-5e3d0283beee4921980ad7b5597d85a9.jpg'),
  (3, true, 'Vegetable Tempura Roll', 'Crispy tempura-battered vegetables in a sushi roll', 10.00, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://c.ndtvimg.com/2023-10/7h05mcqg_veg-tempura-roll_625x300_04_October_23.jpg'),
  (3, true, 'Avocado Cucumber Roll', 'Sushi roll filled with creamy avocado and crisp cucumber', 9.00, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://pureella.com/wp-content/uploads/Pure-Ella_-Ella-Leche-Cucumber-Rolls-with-avocado-vegan-and-gluten-free-photo4.jpg'),
  (3, true, 'Inari Sushi', 'Sweet tofu pockets filled with seasoned sushi rice', 8.50, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://i2.wp.com/mayakitchenette.com/wp-content/uploads/2015/01/easy-inari-sushi-recipe-1-4.jpg?ssl=1'),
  (3, true, 'Miso Glazed Eggplant Nigiri', 'Grilled eggplant nigiri with a savory miso glaze', 9.50, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://www.justonecookbook.com/wp-content/uploads/2021/10/Miso-Glazed-Eggplants-3368-I-1-480x270.jpg'),
  (3, true, 'Vegetable Hand Roll', 'Hand roll with fresh vegetables and sushi rice wrapped in seaweed', 7.50, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://gardenfreshfoodie.com/wp-content/uploads/2015/07/Summer-Veggie-Hand-Rolls-With-Wasabi-Soy-Sauce_LR-Watermark.jpg'),
  (3, true, 'Crispy Tofu Maki', 'Crunchy tempura tofu maki roll with tangy dipping sauce', 11.00, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://cdn.foodaciously.com/static/recipes/6c091a00-922d-48d9-b87c-ce2d364580f9/vegan-crunchiy-california-rolls-with-tofu-08c0ea7eeb121ea89055bbc92a83a9bd-1920-q80.jpg'),
  (3, true, 'Asparagus Nigiri', 'Fresh asparagus atop seasoned sushi rice', 8.00, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSACLFWG_O3rWReyfKExqidBISLvM5D7Z0Ukg&usqp=CAU'),
  (3, true, 'Pickled Radish Roll', 'Colorful roll with pickled radish, avocado, and sushi rice', 9.00, '{"vegetarian", "normal"}', '{"japanese", "rice"}', 'https://www.japanesefoodguide.com/wp-content/uploads/2023/04/pickled-daikon-radish-sushi-1024x683.jpg.webp'),
  (3, true, 'Salmon Nigiri', 'Fresh salmon slices over seasoned sushi rice', 9.00, 'normal', '{"japanese", "rice"}', 'https://www.manusmenu.com/wp-content/uploads/2013/09/1-Salmon-Nigiri-1-1-of-1.jpg'),
  (3, true, 'Tuna Sashimi', 'Buttery tuna slices served sashimi-style', 12.00, 'normal', '{"japanese", "sashimi", "tuna"}', 'https://www.kikkoman.com/en/cookbook/assets/img/GlossaryTuna.jpg'),
  (3, true, 'Spicy Tuna Roll', 'Sushi roll with spicy tuna and avocado', 11.00, 'normal', '{"japanese", "rice"}', 'https://www.tiger-corporation.com/wp-content/uploads/2023/02/hero-img-recipe-spicy-tuna-3db6e125056f2bde01321a3da5d290da.jpg'),
  (3, true, 'Prawn Tempura Uramaki', 'Inside-out sushi roll with crispy prawn tempura', 13.00, 'normal', '{"japanese", "rice"}', 'https://preview.redd.it/uej4ao9cyts81.jpg?width=640&crop=smart&auto=webp&s=b30dc2e08b70c091a52305839c52b2df56d4bee3'),



  -- Korean Spicy Noodle House
  (4, true, 'Spicy Ramen', 'Fiery ramen with spicy broth', 10.00, 'normal', '{"korean", "noodles"}', 'https://myspicetrunk.com/wp-content/uploads/2021/04/WhatsApp-Image-2021-04-15-at-2.30.17-PM-e1618525005703.jpeg?v=1618524592'),
  (4, true, 'Kimchi Udon', 'Udon noodles with kimchi and vegetables', 11.50, 'normal', '{"korean", "noodles"}', 'https://omnivorescookbook.com/wp-content/uploads/2022/05/220419_-Kimchi-Udon-Stir-Fry-With-Bacon_550.jpg'),
  (4, true, 'Bibimbap', 'Mixed rice with vegetables, beef, and a spicy sauce', 12.00, 'normal', '{"korean", "rice"}', 'https://www.seriouseats.com/thmb/9gYczIvS4R7ZvK19ahBns0xOG_k=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230113-Bibimbap-AmandaSuarez-hero-331e5e1ffa5b400fbb684e59b14d57c1.JPG'),
  (4, true, 'Spicy Kimchi Fried Rice', 'Fried rice with spicy kimchi and pork', 10.50, 'normal', '{"korean", "rice"}', 'https://omnivorescookbook.com/wp-content/uploads/2020/08/200806_Kimchi-Fried-Rice_550.jpg'),
  
  -- Pizza Paradise
  (5, true, 'Margherita Pizza', 'Classic pizza with tomato, mozzarella, and basil', 14.00, 'normal', '{"italian", "american"}', 'https://uk.ooni.com/cdn/shop/articles/20220211142645-margherita-9920.jpg?crop=center&height=800&v=1660843558&width=800'),
  (5, true, 'Pepperoni Delight', 'Pizza topped with pepperoni and cheese', 16.50, 'normal', '{"italian", "american"}', 'https://img.freepik.com/premium-photo/pepperoni-pizza-bliss-spicy-pepperoni-delight-cheesy-goodness-capturing-irresistible-slice_971975-3479.jpg'),
  (5, true, 'Seafood Pizza', 'Pizza topped with assorted seafood and herbs', 17.00, 'normal', '{"italian", "american"}', 'https://insanelygoodrecipes.com/wp-content/uploads/2022/11/Homemade-Italian-Seafood-Pizza-with-Shrimp-Clam-and-Mussels.jpg'),
  (5, true, 'Vegetarian Supreme', 'Pizza loaded with assorted vegetables and cheese', 15.50, '{"vegetarian", "normal"}', '{"italian", "american"}', 'https://i0.wp.com/www.thursdaynightpizza.com/wp-content/uploads/2022/06/veggie-pizza-side-view-out-of-oven.png?resize=720%2C480&ssl=1'),

  -- Curry House
  (6, true, 'Chicken Curry', 'Spicy chicken curry with fragrant rice', 9.00, '{"halal", "normal"}', '{"indian", "rice"}', 'https://www.recipetineats.com/wp-content/uploads/2023/10/African-coconut-chicken-curry_3.jpg?w=500&h=500&crop=1'),
  (6, true, 'Vegetable Biryani', 'Flavorful biryani with mixed vegetables', 11.00, '{"halal", "vegetatian", "normal"}', '{"indian", "rice"}', 'https://img.taste.com.au/_L7m5vxs/taste/2016/11/vegetable-biryani-102620-1.jpeg'),
  (6, true, 'Butter Chicken', 'Creamy and flavorful butter chicken curry', 12.00, '{"halal", "normal"}', 'indian', 'https://cravinghomecooked.com/wp-content/uploads/2020/06/butter-chicken-1.jpg'),
  (6, true, 'Paneer Tikka Masala', 'Paneer in a spicy tomato-based curry', 13.50, '{"halal", "vegetarian", "normal"}', '{"indian", "rice"}', 'https://healthynibblesandbits.com/wp-content/uploads/2019/07/Paneer-Tikka-Masala-5.jpg'),
   (6, true, 'Masala Dosa', 'Crispy crepe filled with spiced potatoes', 8.50, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://recipes.net/wp-content/uploads/2023/05/masala-dosa-recipe_d563150be0b0109e2b9ef6e2d6a51c0e.jpeg'),
  (6, true, 'Chana Masala', 'Spiced chickpea curry with aromatic spices', 10.00, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/chana-masala-recipe.jpg'),
  (6, true, 'Palak Paneer', 'Cottage cheese cubes in a creamy spinach curry', 12.00, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://healthynibblesandbits.com/wp-content/uploads/2020/01/Saag-Paneer-FF.jpg'),
  (6, true, 'Aloo Gobi', 'Potato and cauliflower cooked with Indian spices', 9.00, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://images.immediate.co.uk/production/volatile/sites/30/2018/04/Roasted_aloo_gobi-a6671e9-scaled.jpg?quality=90&resize=556,505'),
  (6, true, 'Vegetable Korma', 'Assorted vegetables in a creamy, nutty sauce', 11.50, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://myfancypantry.files.wordpress.com/2012/04/untitled-04473.jpg'),
  (6, true, 'Chicken Biryani', 'Flavorful rice cooked with marinated chicken', 14.00, '{"halal", "normal"}', '{"indian", "rice"}', 'https://www.awesomecuisine.com/wp-content/uploads/2007/10/Chicken-Biryani_resized-500x436.jpg'),
  (6, true, 'Mutton Rogan Josh', 'Slow-cooked mutton in a rich, flavorful gravy', 15.00, '{"halal", "normal"}', 'indian', 'https://www.archanaskitchen.com/images/archanaskitchen/1-Author/Shaheen_Ali/Kashmiri_Rogan_Josh.jpg'),
  (6, true, 'Pani Puri', 'Indian street food snack with spiced water and chickpeas', 6.50, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://www.sidechef.com/recipe/3883dffb-5fa2-4ee9-8054-d8de1409899f.jpg'),
  (6, true, 'Rasgulla', 'Spongy Bengali sweet dumplings in sugar syrup', 5.00, '{"halal", "vegetarian", "normal"}', '{"indian", "dessert"}', 'https://cdn.ready-market.com.tw/21cd62de/Templates/pic/ANKO-Rasgulla-1200X1200.jpg?v=1a046a18'),
  (6, true, 'Kadai Paneer', 'Paneer and bell peppers in a spicy tomato-based gravy', 13.00, '{"halal", "vegetarian", "normal"}', '{"indian"}', 'https://www.secondrecipe.com/wp-content/uploads/2020/05/dhaba-style-kadai-paneer-001.jpg'),

  -- Thai Delights
  (7, true, 'Tom Yum Soup', 'Spicy and sour soup with shrimp', 8.50, 'normal', '{"thai", "soup"}', 'https://hot-thai-kitchen.com/wp-content/uploads/2013/03/tom-yum-goong-blog.jpg'),
  (7, true, 'Green Curry Chicken', 'Rich green curry with tender chicken', 10.50, 'normal', '{"thai", "soup"}', 'https://hot-thai-kitchen.com/wp-content/uploads/2022/04/green-curry-new-sq-3.jpg'),
  (7, true, 'Vegetarian Pad Thai', 'Stir-fried rice noodles with tofu and vegetables', 9.00, '{"vegetarian", "normal"}', '{"thai", "noodles"}', 'https://img.taste.com.au/z9EIVHJg/taste/2021/02/10-minute-vegetarian-pad-thai-168946-2.jpg'),
  (7, true, 'Vegan Phat Kaphrao', 'Spicy stir-fried tofu with holy basil', 11.00, '{"vegan", "vegetarian", "normal"}', '{"thai", "stir-fry"}', 'https://www.alphafoodie.com/wp-content/uploads/2020/09/vegan-thai-basil-beef-1-of-1-3.jpeg'),
  (7, true, 'Som Tum Salad', 'Refreshing green papaya salad with peanuts and chili', 8.50, '{"vegetarian", "normal"}', '{"thai", "healthy"}', 'https://www.seriouseats.com/thmb/yKNZ9ICJC5ZNhzcYHdHENxogpFw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210928-Som-Tam-Thai-green-papaya-salad-vicky-wasik-24-f0d666fc609f49a0b9f34897bd2c6303.jpg'),
  (7, true, 'Vegan Red Curry', 'Creamy red curry with mixed vegetables and tofu', 12.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "curry"}', 'https://www.connoisseurusveg.com/wp-content/uploads/2023/04/vegan-red-curry-sq-1.jpg'),
  (7, true, 'Vegetable Spring Rolls', 'Crispy fried spring rolls filled with veggies', 6.50, '{ "vegetarian", "normal"}', '{"thai", "appetizer"}', 'https://www.thecookingcollective.com.au/wp-content/uploads/2022/08/Vegetable-Spring-Rolls-2-1.jpg'),
  (7, true, 'Vegan Larb', 'Spicy minced tofu salad with herbs and lime dressing', 10.00, '{"vegan", "vegetarian", "normal"}', '{"thai", "salad"}', 'https://static01.nyt.com/images/2021/08/11/dining/11Veggie-tofu-larb-a/merlin_188546805_b6a2a32b-5635-46e5-82b6-b11b7ed5ac3f-articleLarge.jpg'),
  (7, true, 'Vegetarian Pad See Ew', 'Stir-fried rice noodles with broccoli and egg', 9.50, '{"vegetarian", "normal"}', '{"thai", "noodles"}', 'https://www.myplantifulcooking.com/wp-content/uploads/2022/11/vegan-pad-see-ew-featured.jpg'),
  (7, true, 'Vegan Massaman Curry', 'Rich and nutty curry with potatoes and tofu', 13.00, '{"vegan", "vegetarian", "normal"}', '{"thai", "curry"}', 'https://images.kitchenstories.io/wagtailOriginalImages/R2456-new-final-photo-2.jpg'),
  (7, true, 'Green Papaya Salad', 'Zesty salad made with shredded green papaya, tomatoes, and peanuts', 7.50, '{"vegetarian", "normal"}', '{"thai", "salad"}', 'https://www.whiskaffair.com/wp-content/uploads/2020/06/Green-Papaya-Salad-2-3.jpg'),
  (7, true, 'Vegan Pad Kaprow', 'Spicy stir-fried tofu with Thai basil', 11.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "rice"}', 'https://joyfuldumplings.com/wp-content/uploads/2021/07/Vegan_Thai_Basil_Stir-fry_Pad_Kra_Pao_3_11zon.jpg'),
  (7, true, 'Beef Panang Curry', 'Tender beef in a rich and spicy Panang curry sauce', 14.50, 'normal', '{"thai", "curry"}', 'https://www.foodandwine.com/thmb/atro54_2GCQAuL_BfcWOHg094xs=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Penang-Curry-FT-RECIPE0523-4bd3376f76a648b3b8a30929df61acc5.jpg'),
  (7, true, 'Chicken Satay', 'Grilled marinated chicken skewers served with peanut sauce', 10.00, 'normal', '{"thai", "appetizer"}', 'https://food.fnr.sndimg.com/content/dam/images/food/plus/fullset/2020/02/06/0/FNK-Live_112119-Jet-Tila-Chicken-Satay-with-Peanut-Sauce-0005_s4x3.jpg.rend.hgtvcom.616.462.suffix/1581032331905.jpeg'),
  (7, true, 'Pork Basil Stir Fry', 'Stir-fried pork with Thai basil and spicy sauce', 12.00, 'normal', '{"thai", "stir-fry"}', 'https://images.services.kitchenstories.io/MRxcM_KNscGAJaphGq57qFKQWJ8=/3840x0/filters:quality(85)/images.kitchenstories.io/wagtailOriginalImages/R2592-final-photo.jpg'),
  (7, true, 'Thai Iced Tea', 'Sweet and creamy iced tea made with condensed milk', 3.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://www.thespruceeats.com/thmb/w16B4MH-a_AlvG4t27cw3KgrjLM=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/SES-real-thai-iced-tea-recipe-765458-hero-1-9139caef4772411bb34a948c5df50cfb.jpg'),
  (7, true, 'Fresh Coconut Water', 'Refreshing coconut water served straight from the coconut', 4.00, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://images.squarespace-cdn.com/content/v1/5c1074accc8fed6a4251da8f/4882b78a-b5d4-47a1-a9a0-d05a4fdbd724/shutterstock_490174816.jpg'),
  (7, true, 'Mango Sticky Rice Smoothie', 'Indulgent smoothie inspired by the popular Thai dessert', 5.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://media-cdn.tripadvisor.com/media/photo-p/12/87/06/dc/mango-sticky-rice-smoothie.jpg'),
  (7, true, 'Thai Lemongrass Tea', 'Fragrant tea made with lemongrass and spices', 3.00, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://www.tastythais.com/wp-content/uploads/2020/02/thai-lemongrass-tea.jpg'),
  (7, true, 'Watermelon Cooler', 'Refreshing watermelon drinks with a hint of mint', 4.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://anothertablespoon.com/wp-content/uploads/2018/06/DSC01615-scaled.jpg'),
  (7, true, 'Thai Basil Seed Drink', 'Healthy and soothing drinks made with basil seeds', 3.50, '{"vegan", "vegetarian", "normal"}', '{"thai", "drinks"}', 'https://foodnaturalthai.igetweb.com/catalog/p_1473291.jpg'),

  -- Dessert Dreamland
  (8, true, 'Mango Sticky Rice', 'Sweet sticky rice topped with fresh mango', 6.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "rice"}', 'https://assets.epicurious.com/photos/62d6c5130fc696fea8e55a9c/4:3/w_3708,h_2781,c_limit/MangoStickyRice_RECIPE_04142022_9683_final.jpg'),
  (8, true, 'Chocolate Lava Cake', 'Decadent chocolate cake with a gooey center', 7.50, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://www.melskitchencafe.com/wp-content/uploads/2023/01/updated-lava-cakes7.jpg'),
  (8, true, 'Durian Ice Cream', 'Creamy durian-flavored ice cream', 7.00, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://i.ytimg.com/vi/RcU0cPksc7k/maxresdefault.jpg'),
  (8, true, 'Pandan Cake', 'Light and fluffy pandan-flavored cake', 6.50, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://thezonghan.com/wp-content/uploads/2015/09/IMG_9618Edited.jpg'),

  -- Healthy Bites
  (9, true, 'Quinoa Salad', 'Nutrient-packed salad with quinoa and veggies', 11.00, '{"halal", "vegan", "vegetarian", "normal"}', 'healthy', 'https://cookingwithayeh.com/wp-content/uploads/2021/09/Quinoa-Salad-0.jpg'),
  (9, true, 'Grilled Salmon', 'Grilled salmon fillet with steamed broccoli', 13.50, '{"halal", "vegan", "vegetarian", "normal"}', 'healthy', 'https://thekitchengirl.com/wp-content/uploads/Grilled-Salmon-a_19-1.jpg'),
  (9, true, 'Avocado Salad', 'Salad with avocado, cherry tomatoes, and mixed greens', 12.50, '{"halal", "vegan", "vegetarian", "normal"}', 'healthy', 'https://www.allrecipes.com/thmb/BIMX_PChQD0xvRn4hLsaPyv9PH4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1124818-156e56b4500b4a3aae1eabe5004850c9.jpg'),
  (9, true, 'Teriyaki Tofu Bowl', 'Bowl with teriyaki tofu, brown rice, and vegetables', 11.00, '{"halal", "vegan", "vegetarian", "normal"}', 'healthy', 'https://www.justonecookbook.com/wp-content/uploads/2022/03/Teriyaki-Tofu-Bowl-6768-I.jpg'),

  -- Western Grill
  (10, true, 'BBQ Ribs', 'Tender BBQ ribs with a savory glaze', 18.00, 'normal', '{"western", "american"}', 'https://www.coles.com.au/content/dam/coles/cusp/recipes-inspiration/pvx/May23-PVX-slow-cooker-BBQ-ribs-976x549.jpg'),
  (10, true, 'Classic Cheeseburger', 'Juicy beef patty with melted cheese', 14.50, 'normal', '{"western", "american"}', 'https://www.unileverfoodsolutions.com.sg/dam/global-ufs/mcos/SEA/calcmenu/recipes/SG-recipes/vegetables-&-vegetable-dishes/%E7%BB%8F%E5%85%B8%E8%8A%9D%E5%A3%AB%E6%B1%89%E5%A0%A1/main-header.jpg'),
  (10, true, 'Surf and Turf', 'Steak and grilled prawns served with a side of mashed potatoes', 20.00, '{"western", "american"}', 'western', 'https://www.krumpli.co.uk/wp-content/uploads/2023/05/Surf-and-Turf-01-735x735.jpg'),
  (10, true, 'Caesar Salad with Grilled Chicken', 'Classic Caesar salad with grilled chicken', 13.50, '{"western", "american", "healthy"}', 'western', 'https://food.fnr.sndimg.com/content/dam/images/food/fullset/2010/3/3/0/FNM_040110-W-N-Dinners-015_s4x3.jpg.rend.hgtvcom.616.462.suffix/1371591380107.jpeg'),
  
  -- Satay Street
  (11, true, 'Chicken Satay', 'Grilled chicken skewers with peanut sauce', 8.00, '{"halal", "normal"}', '{"indonesian", "singaporean"}', 'https://www.kitchensanctuary.com/wp-content/uploads/2015/08/Chicken-Satay-square-FS-7321.jpg'),
  (11, true, 'Beef Satay', 'Grilled beef skewers with a flavorful marinade', 9.00, '{"halal", "normal"}', '{"indonesian", "singaporean"}', 'https://www.dinnerwithjulie.com/wp-content/uploads/2017/01/Beef-Satay-2.jpg'),
  (11, true, 'Satay Platter', 'Assortment of grilled chicken and beef satay skewers', 15.00, '{"halal", "normal"}', '{"indonesian", "singaporean"}', 'https://media-cdn.tripadvisor.com/media/photo-s/05/9e/24/6e/cotton.jpg'),
  (11, true, 'Satay Fried Rice', 'Fried rice with chopped chicken and beef satay', 12.50, '{"halal", "normal"}', '{"indonesian", "singaporean", "rice"}', 'https://www.weightloss.com.au/assets/Uploads/Recipes/satay-fried-rice-with-beef-lge.jpg'),

  -- Dim Sum Delight
  (12, true, 'Har Gow', 'Steamed shrimp dumplings with a thin translucent skin', 5.50, 'normal', '{"chinese", "singaporean"}', 'https://media-cdn2.greatbritishchefs.com/media/nd3bemis/img34601.whqc_768x512q80.jpg'),
  (12, true, 'Siu Mai', 'Steamed pork dumplings with a savory filling', 6.50, 'normal', '{"chinese", "singaporean"}', 'https://redhousespice.com/wp-content/uploads/2022/11/dim-sum-siu-mai-scaled.jpg'),
  (12, true, 'Xiao Long Bao', 'Soup dumplings with a burst of flavorful broth inside', 7.50, 'normal', '{"chinese", "singaporean"}', 'https://images.slurrp.com/prod/recipe_images/asian-food-network/din-tai-fung-xiao-long-bao-1623090738_F7XX8Z3F61Q89QQUGZ9H.webp'),
  (12, true, 'Fried Spring Rolls', 'Crispy spring rolls filled with vegetables and shrimp', 6.00, 'normal', '{"chinese", "singaporean"}', 'https://www.sidechef.com/recipe/5ce2fb5d-778f-4adc-b929-d9f9b00b949f.jpg?d=1408x1120'),
  (12, true, 'Vegetarian Spring Rolls', 'Crispy spring rolls filled with vegetables', 6.00, 'vegetarian', '{"chinese", "singaporean"}', 'https://shortgirltallorder.com/wp-content/uploads/2020/08/tofu-fresh-rolls-square.jpg'),

  -- Ramen House
  (13, true, 'Shoyu Ramen', 'Soy-based ramen with tender slices of pork', 10.00, 'normal', '{"japanese", "noodles"}', 'https://www.justonecookbook.com/wp-content/uploads/2023/04/Shoyu-Ramen-8308-I.jpg'),
  (13, true, 'Miso Ramen', 'Ramen in a rich miso broth with vegetables', 11.50, 'normal', '{"japanese", "noodles"}', 'https://assets.tmecosys.com/image/upload/t_web767x639/img/recipe/ras/Assets/601FDD58-68E1-47B8-A925-5A7DA7C8E7DE/Derivates/00ab9024-d404-47ef-810b-c48dcf1fdb39.jpg'),
  (13, true, 'Spicy Tan Tan Ramen', 'Spicy sesame-based broth with ground pork', 12.00, 'normal', '{"japanese", "noodles"}', 'https://i0.wp.com/seonkyounglongest.com/wp-content/uploads/2020/08/tantanmen-05-mini.jpg?fit=1000%2C667&ssl=1'),
  (13, true, 'Vegetarian Miso Ramen', 'Ramen in miso broth with tofu and assorted vegetables', 11.00, 'vegetarian', '{"japanese", "noodles", "healthy"}', 'https://images.squarespace-cdn.com/content/v1/5e185ce3e56525704fdae715/285175dc-3dda-4f26-8136-397d8d61dad6/DSC02846.jpg'),

  -- Mexican Maze
  (14, true, 'Beef Fajitas', 'Sizzling beef strips with peppers and onions, served with tortillas', 14.00, 'normal', '{"mexican", "western"}', 'https://www.simplejoy.com/wp-content/uploads/2019/12/steak-fajitas.jpg'),
  (14, true, 'Chicken Enchiladas', 'Corn tortillas filled with seasoned chicken, cheese, and topped with sauce', 12.50, 'normal',  '{"mexican", "western"}', 'https://www.southernliving.com/thmb/ZsA5vkPXFkt2a0gBWftIH7H-B-I=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/ChickenEnchiladas_Beauty_4_SEO53_322-27c2f3140952481bb8a81d58501f6e54.jpg'),
  (14, true, 'Queso Dip', 'Creamy cheese dip served with tortilla chips', 8.50, '{"vegetarian", "normal"}',  '{"mexican", "western"}', 'https://hips.hearstapps.com/hmg-prod/images/queso-horizontal-1546454862.png?crop=1xw:0.843328335832084xh;center,top&resize=1200:*'),
  (14, true, 'Chili Con Carne', 'Hearty beef and bean chili with a hint of spice', 10.00, 'normal',  '{"mexican", "western"}', 'https://www.allrecipes.com/thmb/jkfRQlj_grQQU3KvD-2Z3k3Sa_Q=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/89993-award-winning-chili-con-carne-ddmfs-3x4-4e3a48f5505a4c998415c261507b0a76.jpg'),
  (14, true, 'Fish Tacos', 'Crispy fish in soft tortillas with slaw and creamy dressing', 13.00, 'normal',  '{"mexican", "western"}', 'https://thecozyapron.com/wp-content/uploads/2018/03/baja-fish-tacos_thecozyapron_1.jpg'),
  (14, true, 'Vegetarian Burrito Bowl', 'Rice, beans, vegetables, and toppings in a bowl', 11.00, '{"vegan", "vegetarian", "normal"}', '{"mexican", "western"}', 'https://playswellwithbutter.com/wp-content/uploads/2022/06/Veggie-Burrito-Bowls-with-Green-Rice-Vegan-Vegetarian-11.jpg'),
  (14, true, 'Tamale Pie', 'Cornmeal crust filled with seasoned meat, beans, and cheese', 9.50, 'normal',  '{"mexican", "western"}', 'https://keviniscooking.com/wp-content/uploads/2021/08/Easy-Tamale-Casserole-square.jpg'),
  (14, true, 'Mexican Street Corn', 'Grilled corn topped with cheese, spices, and herbs', 6.50, 'vegetarian',  '{"mexican", "western"}', 'https://www.seriouseats.com/thmb/6tXTfp2-QGmVLazenk672sgUdRw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20210630-elotes-melissa-hom-seriouseats-5-895932860b0d4f88b1b330e574036305.jpg'),
  (14, true, 'Sopapillas', 'Fried pastry topped with cinnamon and honey', 7.00, '{"vegan", "vegetarian", "normal"}',  '{"mexican", "western"}', 'https://www.thespruceeats.com/thmb/XpAczaZ4KW_3YWCLpZ_fEcl8hqo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/SES-sopapillas-recipe-7187450-hero-A-357ed80837874b67b89845509866df85.jpg'),
  (14, true, 'Margarita Cocktail', 'Classic tequila-based cocktail with lime and salt rim', 8.00, 'normal',  '{"mexican", "western", "drinks"}', 'https://www.seriouseats.com/thmb/rkmijvOtxOQyH3D8n2q8uc67XNk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/__opt__aboutcom__coeus__resources__content_migration__serious_eats__seriouseats.com__recipes__images__2015__04__20150323-cocktails-vicky-wasik-margarita-c84b154e757d43688de15dc8f8ca0de9.jpg'),

 -- Vegetarian Paradise
  (15, true, 'Vegetable Stir-Fry', 'Assorted fresh vegetables stir-fried in a savory sauce', 12.00, '{"vegan", "vegetarian", "normal"}', '{"chinese", "italian", "healthy"}', 'https://www.wholesomeyum.com/wp-content/uploads/2020/11/wholesomeyum-Stir-Fry-Vegetables-15.jpg'),
  (15, true, 'Mushroom Risotto', 'Creamy Italian risotto cooked with mushrooms and parmesan cheese', 14.50, '{"vegetarian", "normal"}', '{"western", "italian", "healthy"}', 'https://www.allrecipes.com/thmb/Pow6PE9UyushNDB4wutXNnmriX8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/85389-gourmet-mushroom-risotto-86-7a2d218f53e94ccfaecc69b6fd93cab8.jpg'),
  (15, true, 'Spinach and Ricotta Stuffed Shells', 'Pasta shells filled with spinach, ricotta, and topped with marinara sauce', 13.00, '{"vegan", "vegetarian", "normal"}', '{"western", "italian", "mexican", "healthy"}', 'https://www.perfectitaliano.com.au/content/dam/perfectitaliano-aus/recipe/0_desktop/Desktop-Pumpkin-Spinach-Ricotta-Pasta-Shells.jpg'),
  (15, true, 'Falafel Platter', 'Crispy chickpea patties served with hummus, pita, and salad', 11.00, '{"vegetarian", "normal"}', '{"western", "indian", "healthy"}', 'https://images.food52.com/w-AqlyOh66Dol7IeeK8v9VSBCOI=/2016x1344/filters:format(webp)/2ad1aa5b-2304-4c05-b575-9e1fc8165e33--falafel_3_01.JPG'),
  (15, true, 'Eggplant Parmesan', 'Layered eggplant slices baked with marinara sauce and melted cheese', 12.00, '{"vegetarian", "normal"}', '{"western", "italian", "chinese", "healthy"}', 'https://www.allrecipes.com/thmb/L9wpL6T8bgfo7C09-Euoa-OSN0A=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/25321-eggplant-parmesan-ii-DDMFS-4x3-6d53ce79765b4c3d9f554d2a47e14d00.jpg'),
  (15, true, 'Quinoa Salad', 'Colorful salad with quinoa, mixed vegetables, feta cheese, and a citrus dressing', 10.50, '{"vegan", "vegetarian", "normal"}', '{"western", "italian", "healthy"}', 'https://cookingwithayeh.com/wp-content/uploads/2021/09/Quinoa-Salad-0.jpg'),
  (15, true, 'Vegetarian Pad Thai', 'Thai stir-fried noodles with tofu, veggies, and a tangy sauce', 13.50, '{"vegan", "vegetarian", "normal"}', '{"western", "thai", "healthy"}', 'https://realfood.tesco.com/media/images/Veg-Pad-Thai-LGH-069d45e9-fd6c-44d1-b747-83dbac2d921d-0-1400x919.jpg'),
  (15, true, 'Portobello Mushroom Burger', 'Juicy grilled portobello mushroom served on a bun with toppings', 11.50, '{"vegan", "vegetarian", "normal"}', '{"western", "american", "healthy"}', 'https://www.eatingwell.com/thmb/tShM0ln-RbhCdY4O5Bfq5c43DjE=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/7606814-c5af110e32e848a282294d71ba1bb708.jpg'),
  (15, true, 'Coconut Curry Lentils', 'Creamy coconut curry with lentils, served with rice', 11.50, '{"vegetarian", "normal"}', '{"indian", "healthy"}', 'https://www.budgetbytes.com/wp-content/uploads/2019/07/Creamy-Coconut-Curry-Lentils-with-Spinach-dip-naan.jpg'),
  (15, true, 'Avocado Toast', 'Crusty bread topped with mashed avocado, cherry tomatoes, and a sprinkle of seasoning', 9.00, '{"vegan", "vegetarian", "normal"}', '{"western", "italian", "healthy"}', 'https://www.eatingwell.com/thmb/CTSAuY2CRbo0Ivw4wbfIydhy7Qw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/1807w-avocado-toast-recipe-8029771-2000-aefaa92c11e74e80b0bfc15788a61465.jpg'),


-- Vegan Delights
(16, true, 'Spicy Cauliflower Wings', 'Crispy baked cauliflower florets tossed in spicy sauce', 10.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "chinese", "healthy", "singaporean"}', 'https://www.eatingwell.com/thmb/q09unCog3g7x75xiNPD4FqgNVUY=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/sriracha-buffalo-cauliflower-bites-step-09-b9a69156ce184797a415159f12cb93a1.jpg'),
(16, true, 'Lentil Shepherds Pie', 'Hearty lentil filling topped with mashed potatoes, baked to perfection', 14.50, '{"vegan", "vegetarian", "normal"}', '{"vegan", "western", "singaporean"}', 'https://tastythriftytimely.com/wp-content/uploads/2023/01/Lentil-Shepherds-Pie-Featured.jpg'),
(16, true, 'Vegan Tacos', 'Black bean, corn, and avocado-filled tacos served with salsa', 12.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "itatian", "western", "healthy"}', 'https://umamigirl.com/wp-content/uploads/2022/01/Black-Bean-Vegan-Tacos-Umami-Girl-1200-7.jpg'),
(16, true, 'Chickpea Shawarma Wrap', 'Marinated chickpeas with tahini sauce wrapped in a warm pita', 11.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "indian", "western", "healthy"}', 'https://static.ffx.io/images/$zoom_1%2C$multiply_0.2929%2C$ratio_1.777778%2C$width_1994%2C$x_6%2C$y_285/t_crop_custom/q_86%2Cf_auto/4b31216987e825e3dfc44d53f7ada8ae49e33c84'),
(16, true, 'Quinoa Stuffed Bell Peppers', 'Bell peppers filled with quinoa, black beans, and spices', 13.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "indian", "western", "singaporean"}', 'https://i0.wp.com/bakeatmidnite.com/wp-content/uploads/2014/03/quinoa-stuffed-peppers-1-43-o.jpg'),
(16, true, 'Coconut Curry Tofu', 'Creamy coconut curry with crispy tofu, served with rice', 12.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "singaporean", "chinese", "healthy"}', 'https://www.ambitiouskitchen.com/wp-content/uploads/fly-images/27301/tofucurry-1-500x500-c.jpg'),
(16, true, 'Vegan Pizza', 'Thin-crust pizza topped with veggies, dairy-free cheese, and marinara sauce', 13.50, '{"vegan", "vegetarian", "normal"}', '{"vegan", "italian", "western"}', 'https://cdn.loveandlemons.com/wp-content/uploads/2018/09/vegan-pizza.jpg'),
(16, true, 'Zucchini Noodles with Pesto', 'Spiralized zucchini noodles tossed in homemade vegan pesto sauce', 11.50, '{"vegan", "vegetarian", "normal"}', '{"vegan", "italian", "western", "noodles"}', 'https://www.twopeasandtheirpod.com/wp-content/uploads/2013/08/Zucchini-Noodles-with-Pesto-7.jpg'),
(16, true, 'Vegan Sushi Roll', 'Colorful sushi roll filled with avocado, cucumber, and pickled veggies', 12.50, '{"vegan", "vegetarian", "normal"}', '{"vegan", "healthy", "japanese"}', 'https://www.justonecookbook.com/wp-content/uploads/2023/05/Vegetarian-Sushi-Rolls-9707-I-1.jpg'),
(16, true, 'Chocolate Avocado Mousse', 'Decadent chocolate mousse made with avocado for a creamy texture', 8.00, '{"vegan", "vegetarian", "normal"}', '{"vegan", "dessert", "western"}', 'https://img.taste.com.au/2SwT0nAy/taste/2016/11/dairy-free-avocado-chocolate-mousse-90600-1.jpeg');
