 -- Dessert Dreamland
  (8, true, 'Mango Sticky Rice', 'Sweet sticky rice topped with fresh mango', 6.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "rice"}', 'https://hot-thai-kitchen.com/wp-content/uploads/2022/09/Mango-sticky-rice-blog.jpg'),
  (8, true, 'Chocolate Lava Cake', 'Decadent chocolate cake with a gooey center', 7.50, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://www.melskitchencafe.com/wp-content/uploads/2023/01/updated-lava-cakes7.jpg'),
  (8, true, 'Durian Ice Cream', 'Creamy durian-flavored ice cream', 7.00, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://static.wixstatic.com/media/917655_7ef06e67d684486eace3f08abeef8047~mv2.jpg/v1/crop/x_488,y_2581,w_2577,h_1900/fill/w_570,h_422,al_c,q_80,usm_0.66_1.00_0.01,enc_auto/Durian%20-%20Vertical.jpg'),
  (8, true, 'Pandan Cake', 'Light and fluffy pandan-flavored cake', 6.50, '{"halal", "vegan", "vegetarian", "normal"}', 'dessert', 'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_1:1/k%2FPhoto%2FRecipes%2F2023-01-pandan-cake%2Fpandan-cake-002'),

    (8, true, 'Coconut Sorbet', 'Refreshing sorbet made with coconut milk', 5.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "sorbet"}', 'https://www.manusmenu.com/wp-content/uploads/2014/09/1-Coconut-Ice-Cream-1-1-of-1.jpg'),
  (8, true, 'Matcha Tiramisu', 'Green tea-infused tiramisu with a Japanese twist', 8.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "tiramisu"}', 'https://fullofplants.com/wp-content/uploads/2022/10/vegan-matcha-tiramisu-with-matcha-sponge-cake-delicious-dairy-free-dessert-thumb-3.jpg'),
  (8, true, 'Lychee Panna Cotta', 'Creamy panna cotta flavored with fragrant lychee', 6.50, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "panna cotta"}', 'https://yummyaddiction.com/wp-content/uploads/2023/03/tropical-panna-cotta-featured.jpg'),
  (8, true, 'Red Bean Mochi', 'Chewy mochi filled with sweet red bean paste', 5.50, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "mochi"}', 'https://www.ohmyfoodrecipes.com/wp-content/uploads/2020/04/red-bean-mochi-open.jpg'),
  (8, true, 'Thai Mango Sticky Rice Sundae', 'Classic Thai dessert in a sundae form with coconut ice cream', 7.50, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "ice cream"}', 'https://preview.redd.it/what-can-be-better-than-mango-sticky-rice-mango-sticky-rice-v0-ir7v7n4kxeja1.jpg?auto=webp&s=b157fbeed427fb153cfbfc5fcb319792e1864ba3'),
  (8, true, 'Black Sesame Pudding', 'Rich and nutty black sesame pudding', 6.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "pudding"}', 'https://onolicioushawaii.com/wp-content/uploads/2021/06/Black-Sesame-Pudding-9-720x720.jpg'),
  (8, true, 'Pistachio Baklava', 'Layers of flaky pastry filled with pistachios and honey', 9.00, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "baklava"}', 'https://www.thespruceeats.com/thmb/CdcbG-kgftT4dzyumCNbI2tYwsk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/PistachioBaklava-GettyImages-183422455-5997abb09abed50010b57402.jpg'),
  (8, true, 'Mochi Ice Cream', 'Japanese confection of ice cream wrapped in sweet rice dough', 5.50, '{"halal", "vegan", "vegetarian", "normal"}', '{"dessert", "ice cream"}', 'https://www.justonecookbook.com/wp-content/uploads/2020/08/Mochi-Ice-Cream-8680-I.jpg');