// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	null "gopkg.in/guregu/null.v4"
)

// Stores cuisine
type Cuisine struct {
	ID      int64       `json:"id"`
	Cuisine null.String `json:"cuisine"`
}

// Stores dishes
type Dish struct {
	ID           int64       `json:"id"`
	RestaurantID int64       `json:"restaurant_id"`
	IsAvailable  bool        `json:"is_available"`
	Name         string      `json:"name"`
	Description  null.String `json:"description"`
	Price        float64     `json:"price"`
	Cuisine      null.String `json:"cuisine"`
	ImageUrl     null.String `json:"image_url"`
}

// Stores user playlist
type Playlist struct {
	ID        int64       `json:"id"`
	Name      string      `json:"name"`
	Image     null.String `json:"image"`
	FoodItems null.String `json:"food_items"`
	IsActive  bool        `json:"is_active"`
	CreatedOn time.Time   `json:"created_on"`
}

// Stores restaurants
type Restaurant struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description null.String `json:"description"`
	Address     null.String `json:"address"`
	Rating      null.Float  `json:"rating"`
	Cuisine     null.String `json:"cuisine"`
	ImageUrl    null.String `json:"image_url"`
}
