// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: playlist.sql

package db

import (
	"context"
)

const createPlaylist = `-- name: CreatePlaylist :one
INSERT INTO playlists (
  name,
  image,
  food_items,
  is_active
) 
VALUES (
  $1, $2, $3, $4
)
RETURNING id, name, image, food_items, is_active, created_on
`

type CreatePlaylistParams struct {
	Name      string `json:"name"`
	Image     string `json:"image"`
	FoodItems string `json:"food_items"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) CreatePlaylist(ctx context.Context, arg CreatePlaylistParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, createPlaylist,
		arg.Name,
		arg.Image,
		arg.FoodItems,
		arg.IsActive,
	)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.FoodItems,
		&i.IsActive,
		&i.CreatedOn,
	)
	return i, err
}

const deletePlaylist = `-- name: DeletePlaylist :exec
DELETE FROM playlists
WHERE id = $1
`

func (q *Queries) DeletePlaylist(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlaylist, id)
	return err
}

const getAllPlaylists = `-- name: GetAllPlaylists :many
SELECT id, name, image, food_items, is_active, created_on FROM playlists
WHERE is_active = true
ORDER BY id
`

func (q *Queries) GetAllPlaylists(ctx context.Context) ([]Playlist, error) {
	rows, err := q.db.QueryContext(ctx, getAllPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Playlist{}
	for rows.Next() {
		var i Playlist
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Image,
			&i.FoodItems,
			&i.IsActive,
			&i.CreatedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFoodItemsFromPlaylists = `-- name: GetFoodItemsFromPlaylists :many
SELECT food_items FROM playlists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFoodItemsFromPlaylists(ctx context.Context, id int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getFoodItemsFromPlaylists, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var food_items string
		if err := rows.Scan(&food_items); err != nil {
			return nil, err
		}
		items = append(items, food_items)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaylist = `-- name: GetPlaylist :one
SELECT id, name, image, food_items, is_active, created_on FROM playlists
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPlaylist(ctx context.Context, id int64) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, getPlaylist, id)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.FoodItems,
		&i.IsActive,
		&i.CreatedOn,
	)
	return i, err
}

const updateIsActive = `-- name: UpdateIsActive :one
UPDATE playlists
SET 
  is_active = $2
WHERE 
  id = $1
RETURNING id, name, image, food_items, is_active, created_on
`

type UpdateIsActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) UpdateIsActive(ctx context.Context, arg UpdateIsActiveParams) (Playlist, error) {
	row := q.db.QueryRowContext(ctx, updateIsActive, arg.ID, arg.IsActive)
	var i Playlist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Image,
		&i.FoodItems,
		&i.IsActive,
		&i.CreatedOn,
	)
	return i, err
}
